Linear Algebra and CNNS

https://medium.com/towards-data-science/linear-algebra-cheat-sheet-for-deep-learning-cd67aba4526c

https://medium.com/impactai/cnns-from-different-viewpoints-fab7f52d159c

https://github.com/fastai/courses/blob/master/deeplearning1/excel/conv-example.xlsx

https://www.youtube.com/watch?v=V2h3IOBDvrA

In [5]:
import numpy
import numpy as np

In [4]:
# Multiply two arrays 
x = [1,2,3]
y = [2,3,4]
product = []
for i in range(len(x)):
    product.append(x[i]*y[i])
# Linear algebra version
x = numpy.array([1,2,3])
y = numpy.array([2,3,4])
x * y

array([ 2,  6, 12])

In [9]:
y = np.array([1,2,3])
x = np.array([2,3,4])
# np.dot(y,x) = 20

np.dot(y,x)

20

In [10]:
y = np.array([1,2,3])
x = np.array([2,3,4])
y * x 

array([ 2,  6, 12])

In [13]:
x.shape

(3,)

In [14]:
a = np.array([
 [1,2,3], 
 [4,5,6]
])

In [15]:
a.shape

(2, 3)

In [16]:
a = np.array([
 [1],
 [2]
])
b = np.array([
 [3,4],
 [5,6]
])
c = np.array([
 [1,2]
])
# # Same no. of rows
# # Different no. of columns
# # but a has one column so this works
# a * b
# [[ 3, 4],
#  [10, 12]]
# # Same no. of columns
# # Different no. of rows
# # but c has one row so this works
# b * c
# [[ 3, 8],
#  [5, 12]]
# # Different no. of columns
# # Different no. of rows
# # but both a and c meet the 
# # size 1 requirement rule
# a + c
# [[2, 3],
#  [3, 4]]

In [17]:
# Same no. of rows
# Different no. of columns
# but a has one column so this works
a * b

array([[ 3,  4],
       [10, 12]])

In [18]:
# # Same no. of columns
# # Different no. of rows
# # but c has one row so this works
b * c



array([[ 3,  8],
       [ 5, 12]])

In [19]:
# # Different no. of columns
# # Different no. of rows
# # but both a and c meet the 
# # size 1 requirement rule
a + c

array([[2, 3],
       [3, 4]])

In [20]:
a = np.array([
   [1, 2], 
   [3, 4]])
a.T
[[1, 3],
 [2, 4]]


[[1, 3], [2, 4]]